root: '2812656625'
bt_uin: '201382404'
enable_webui_interaction: true
debug: false
github_proxy: null
check_ncatbot_update: true
skip_ncatbot_install_check: false
websocket_timeout: 15
napcat:
  ws_uri: ws://localhost:3002
  ws_token: myj123
  ws_listen_ip: localhost
  webui_uri: http://localhost:6099
  webui_token: '!8h!_7eVK<R4H0%s'
  enable_webui: true
  check_napcat_update: false
  stop_napcat: false
  remote_mode: false
  report_self_message: false
  report_forward_message_detail: true
plugin:
  plugins_dir: plugins
  plugin_whitelist: []
  plugin_blacklist: []
  skip_plugin_load: false
